---
- hosts: "{{ hostname }}"
  remote_user: hzadm
  tasks:
    - name: Copying ManCenter.sh script to remote server
      copy:
        src: ManCenter.sh
        dest: /home/hzadm
        mode: '0755'
      when: mancenter == "true"

    - name: Run mancenter stop
      shell: "source /home/hzadm/.bash_profile && nohup /opt/HZ/hazelcast/bin/stopManCenter.sh mancenter"
      when: (action == "restart" or action == "stop") and mancenter == "true"
      register: command_output
      failed_when: command_output.rc != 0

    # Updated task: Added 'when' condition to skip if 'Run mancenter stop' was not executed
    - name: ManCenter stop output
      debug:
        msg: "ManCenter stop output: {{ command_output.stdout }}"
      # Condition ensures this task runs only if the stop task ran successfully and wasn't skipped
      when: (action == "restart" or action == "stop") and mancenter == "true" and not command_output.skipped | default(true)

    - name: Run mancenter start
      shell: "source /home/hzadm/.bash_profile && nohup /opt/HZ/hazelcast/bin/startManCenter.sh mancenter"
      when: (action == "restart" or action == "start") and mancenter == "true"
      register: command_output
      failed_when: command_output.rc != 0

    - name: ManCenter start output
      debug:
        msg: "ManCenter start output: {{ command_output.stdout }}"

  roles:
    - role: cluster-restart
      when: mancenter == "false"
