---
- hosts: "{{ hostname }}"  # Ensure 'hostname' is correctly passed from Jenkins and is a valid inventory host.
  remote_user: hzadm
  tasks:
    - name: Debug hostname variable
      debug:
        msg: "Running playbook on hostname: {{ hostname }}"

    - name: Copying ManCenter.sh script to remote server
      copy:
        src: ManCenter.sh
        dest: /home/hzadm
        mode: '0755'
      when: mancenter | bool  # Fix: Ensuring 'mancenter' is treated as a boolean.

    - name: Run mancenter stop
      shell: "source /home/hzadm/.bash_profile && nohup /opt/HZ/hazelcast/bin/stopManCenter.sh mancenter"
      when: 
        - action in ['restart', 'stop']  # Fix: Cleaner condition syntax.
        - mancenter | bool  # Fix: Ensuring boolean comparison.
      register: stop_command_output

    - name: Debug command output (stop)
      debug:
        var: stop_command_output

    - name: Run mancenter start
      shell: "source /home/hzadm/.bash_profile && nohup /opt/HZ/hazelcast/bin/startManCenter.sh mancenter"
      when: 
        - action in ['restart', 'start']  # Fix: Cleaner condition syntax.
        - mancenter | bool  # Fix: Ensuring boolean comparison.
      register: start_command_output

    - name: Debug command output (start)
      debug:
        var: start_command_output

  roles:
    - role: cluster-restart
      when: not mancenter | bool  # Fix: Ensuring 'mancenter' is treated as a boolean.
