---
- name: Set Hazelcast logging type in hazelcast.xml
  blockinfile:
    path: "/opt/HZ/{{ cluster }}/hazelcast.xml" # {{ cluster }} from extravars
    marker: "# {mark} Hazelcast Logging Configuration"
    block: |
      <property name="hazelcast.logging.type">{{ Logging_type }}</property>
      <property name="hazelcast.diagnostics.enabled">true</property>
      <property name="hazelcast.diagnostics.directory">/opt/HZ/diagnostics</property>
      <property name="hazelcast.diagnostics.metric.level">info</property>
      <property name="hazelcast.diagnostics.invocation.sample.period.seconds">10</property>
      <property name="hazelcast.diagnostics.pending.invocations.period.seconds">30</property>
      <property name="hazelcast.diagnostics.slowoperations.period.seconds">30</property>
      <property name="hazelcast.diagnostics.storeLatency.period.seconds">60</property>
      <property name="hazelcast.diagnostics.stdout">LOGGER</property>

- name: Copy log4j2.xml configuration (if using Log4j2)
  when: Logging_type == "log4j2"
  copy:
    src: "{{ role_path }}/files/log4j2.xml"  # Template this file
    dest: "/opt/HZ/{{ cluster }}_container01/etc/log4j2.xml"
    owner: root
    group: root
    mode: 0644

- name: Set JDK logging configuration (if using JDK)
  when: Logging_type == "jdk"
  copy:
    src: "{{ role_path }}/files/jdk-logging.properties" # Template this file
    dest: "/opt/HZ/{{ cluster }}_container01/etc/jdk-logging.properties"
    owner: root
    group: root
    mode: 0644

- name: Modify startContainer.sh for Log4j2 (if using Log4j2)
  when: Logging_type == "log4j2"
  blockinfile:
    path: "/opt/HZ/hazelcast/bin/startContainer.sh"
    marker: "# {mark} Log4j2 Configuration"
    block: |
      classPath=\$HZ_ROOT/commonlib/log4j-api.jar:\$HZ_ROOT/commonlib/log4j-core.jar:\$classPath
      javaOpts="-Dlog4j.configurationFile=\$HZ_ROOT/\$sName/etc/log4j2.xml \$javaOpts"

- name: Modify startContainer.sh for JDK logging (if using JDK)
  when: Logging_type == "jdk"
  blockinfile:
    path: "/opt/HZ/hazelcast/bin/startContainer.sh"
    marker: "# {mark} JDK Logging Configuration"
    block: |
      javaOpts="-Djava.util.logging.config.file=\$HZ_ROOT/\$sName/etc/jdk-logging.properties \$javaOpts"

- name: Modify mancenter.conf for Log4j2 (if using Log4j2)
  when: Logging_type == "log4j2" and is_mancenter is defined and is_mancenter == "Yes"
  blockinfile:
    path: "/opt/HZ/mancenter/mancenter.conf"
    marker: "# {mark} Log4j2 Configuration"
    block: |
      JAVA_OPTS="-Dlog4j.configurationFile=/opt/HZ/mancenter/log4j2.xml $JAVA_OPTS"

- name: Modify mancenter.conf for JDK logging (if using JDK)
  when: Logging_type == "jdk" and is_mancenter is defined and is_mancenter == "Yes"
  blockinfile:
    path: "/opt/HZ/mancenter/mancenter.conf"
    marker: "# {mark} JDK Logging Configuration"
    block: |
      JAVA_OPTS="-Djava.util.logging.config.file=/opt/HZ/mancenter/jdk-logging.properties $JAVA_OPTS"
