---
- hosts: hazelcast_servers  # Replace with your Hazelcast server group from the inventory
  become: true
  vars_files:
    - "vars/common_vars.yaml"  # Variables common to all environments
    - "group_vars/{{ environment }}.yaml"  # Environment-specific variables

  tasks:
    - name: Include tasks based on logging type
      include_tasks: "roles/hazelcast_configuration/tasks/configure_logging.yaml"

    - name: Restart Hazelcast servers (rolling update)
      include_tasks: "roles/hazelcast_management/tasks/rolling_restart.yaml"
      vars:
        cluster_name: "{{ cluster }}" # From pipeline's extravars
        container_name: "container01" # Or loop through containers if needed
